# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dostupné bydlení Vrátkov
description: Nadstandardní rodinné domy 4+KK. První etapa jedenácti domů bude dokončena v létě 2022.
keywords: Vrátkov, Bydlení, rodinné domy
author: Jiří Štěpánek
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bydlenivratkov.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


